### PR TITLE
Fix notification bug

### LINKED ISSUE #1: can't show specified number of notifications

### PR DESCRIPTION
**Pull request by kenta7777**
This PR fixes #1, #2.

### CODE REVIEW

File: background.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 // create an alarm
-chrome.alarms.create('read later notifier', { delayInMinutes : 1, periodInMinutes : 1 });
+chrome.alarms.create('read later notifier', { delayInMinutes : 1, periodInMinutes : 2 });
```
Comment (kenta7777) [inline background.js]: Fix 2 to 10

**Review by kenta7777 — COMMENTED** [review]
LGTM

File: background.js (hunk 1 above)
Comment (kenta7777) [reply background.js]: Fix in [this commit](https://github.com/kenta7777/read-later-notifier/pull/7/commits/3bd1e22a07f104ef777ad9a4a586aacb6861bc45)
